additional types for SAP Gateway
abaplint/deps pull request #75
Opened 2021-06-19 12:55 UTC by gregorwolf

2021-06-19 13:07 UTC, larshp requested changes
.

2021-06-19 13:32 UTC, gregorwolf commented
?

2021-06-19 13:33 UTC, gregorwolf commented
Can't see what change you requested.

2021-06-19 13:57 UTC, gregorwolf commented
Better?

2021-06-19 14:08 UTC, larshp commented on src/gateway/#iwbep#cl_mgw_abs_data.clas.abap
> +    RAISE EXCEPTION TYPE /iwbep/cx_mgw_tech_exception
just leave the method implementations blank or "RETURN.", its not needed for linting

2021-08-16 15:22 UTC, larshp requested changes
see above

2021-09-11 11:54 UTC, larshp commented
closing

2021-09-11 11:54 UTC, closed without merging